import type { SupplyEntity } from './types'

// Semiconductor supply chain entities relevant to a memory/foundry maker (PoC data)
export const ENTITIES: SupplyEntity[] = [
  {
    id: 'tsmc',
    name: 'TSMC',
    nameKo: '대만 TSMC',
    type: 'supplier',
    tier: 1,
    category: '파운드리 (Foundry)',
    country: 'Taiwan',
    city: 'Hsinchu',
    lat: 24.7736,
    lng: 120.9967,
    criticality: 'high',
    status: 'watch',
    products: ['3nm/5nm 위탁생산', 'CoWoS 패키징'],
    activeRiskIds: ['n01', 'n07'],
  },
  {
    id: 'asml',
    name: 'ASML',
    nameKo: '네덜란드 ASML',
    type: 'supplier',
    tier: 1,
    category: 'EUV 노광장비',
    country: 'Netherlands',
    city: 'Veldhoven',
    lat: 51.42,
    lng: 5.403,
    criticality: 'high',
    status: 'watch',
    products: ['EUV 스캐너', 'High-NA EUV', '유지보수 부품'],
    activeRiskIds: ['n02'],
  },
  {
    id: 'shinetsu',
    name: 'Shin-Etsu Chemical',
    nameKo: '신에츠화학',
    type: 'supplier',
    tier: 1,
    category: '실리콘 웨이퍼 / 포토레지스트',
    country: 'Japan',
    city: 'Shirakawa (Fukushima)',
    lat: 37.1264,
    lng: 140.2117,
    criticality: 'high',
    status: 'disrupted',
    products: ['300mm 웨이퍼', 'EUV 포토레지스트'],
    activeRiskIds: ['n03', 'n11'],
  },
  {
    id: 'sumco',
    name: 'SUMCO',
    nameKo: '섬코',
    type: 'supplier',
    tier: 1,
    category: '실리콘 웨이퍼',
    country: 'Japan',
    city: 'Imari (Saga)',
    lat: 33.265,
    lng: 129.879,
    criticality: 'high',
    status: 'normal',
    products: ['300mm 프라임 웨이퍼', '에피 웨이퍼'],
    activeRiskIds: [],
  },
  {
    id: 'jsr',
    name: 'JSR Corporation',
    nameKo: 'JSR',
    type: 'supplier',
    tier: 2,
    category: '포토레지스트',
    country: 'Japan',
    city: 'Yokkaichi (Mie)',
    lat: 34.965,
    lng: 136.624,
    criticality: 'high',
    status: 'watch',
    products: ['ArF 포토레지스트', 'EUV 포토레지스트'],
    activeRiskIds: ['n11'],
  },
  {
    id: 'tel',
    name: 'Tokyo Electron',
    nameKo: '도쿄일렉트론',
    type: 'supplier',
    tier: 1,
    category: '증착·식각 장비',
    country: 'Japan',
    city: 'Sendai (Miyagi)',
    lat: 38.2688,
    lng: 140.8721,
    criticality: 'high',
    status: 'normal',
    products: ['코터/디벨로퍼', '에처', '증착장비'],
    activeRiskIds: [],
  },
  {
    id: 'amat',
    name: 'Applied Materials',
    nameKo: '어플라이드 머티어리얼즈',
    type: 'supplier',
    tier: 1,
    category: '전공정 장비',
    country: 'United States',
    city: 'Santa Clara, CA',
    lat: 37.3541,
    lng: -121.9552,
    criticality: 'high',
    status: 'watch',
    products: ['CVD/PVD 장비', 'CMP 장비', 'ion implant'],
    activeRiskIds: ['n07'],
  },
  {
    id: 'entegris',
    name: 'Entegris',
    nameKo: '엔테그리스',
    type: 'supplier',
    tier: 2,
    category: 'CMP 슬러리 / 필터',
    country: 'Taiwan',
    city: 'Kaohsiung',
    lat: 22.6273,
    lng: 120.3014,
    criticality: 'medium',
    status: 'normal',
    products: ['CMP 슬러리', '가스 필터', '웨이퍼 캐리어'],
    activeRiskIds: ['n01'],
  },
  {
    id: 'merck',
    name: 'Merck Electronics',
    nameKo: '머크 일렉트로닉스',
    type: 'supplier',
    tier: 2,
    category: '특수 화학소재',
    country: 'Germany',
    city: 'Darmstadt',
    lat: 49.8728,
    lng: 8.6512,
    criticality: 'medium',
    status: 'normal',
    products: ['유전체 소재', '컨덕터 소재', '패터닝 소재'],
    activeRiskIds: [],
  },
  {
    id: 'neon-ua',
    name: 'Iceblick / Cryoin (Neon Gas)',
    nameKo: '우크라이나 네온가스',
    type: 'material',
    tier: 3,
    category: '희귀가스 (네온)',
    country: 'Ukraine',
    city: 'Odesa',
    lat: 46.4825,
    lng: 30.7233,
    criticality: 'high',
    status: 'disrupted',
    products: ['네온', '크립톤', '제논'],
    activeRiskIds: ['n05'],
  },
  {
    id: 'hoya',
    name: 'HOYA',
    nameKo: '호야',
    type: 'supplier',
    tier: 2,
    category: '포토마스크 블랭크',
    country: 'Japan',
    city: 'Hachioji (Tokyo)',
    lat: 35.658,
    lng: 139.316,
    criticality: 'high',
    status: 'normal',
    products: ['EUV 마스크 블랭크', '포토마스크 블랭크'],
    activeRiskIds: [],
  },
  {
    id: 'samsung-giheung',
    name: 'Home Fab · Giheung',
    nameKo: '자사 기흥 캠퍼스',
    type: 'site',
    tier: 1,
    category: '자사 생산거점',
    country: 'South Korea',
    city: 'Yongin (Giheung)',
    lat: 37.21,
    lng: 127.1,
    criticality: 'high',
    status: 'normal',
    products: ['DRAM', 'NAND', 'System LSI'],
    activeRiskIds: ['n05', 'n09'],
  },
]

export function getEntity(id: string) {
  return ENTITIES.find((e) => e.id === id)
}
